### ISSUE TITLE
希望进行更深入的研究

### ISSUE THREAD

**Issue by forhuan** [2512500960/ikuaifw#1]
https://www.hxwglm.com/thread-12792-1-1.html
https://wusiyu.me/2022-ikuai-non-cloud-background-activities/

**Comment by 2512500960** [comment]
研究点儿啥呢

**Comment by forhuan** [comment]
比如上传用户隐私、远控、偷跑流量？ pmd里面东西不少呢。
或者魔改fw?

**Comment by Score2** [comment]
![image](https://github.com/2512500960/ikuaifw/assets/16173457/be272699-be58-4fca-8d03-dba5d037eb8a)
这些是有关于官方包的简单信息
只是初步分析得出

**Comment by forhuan** [comment]
好像在pmd里还看到了ik_rc_client(好像和穿透有关)和cre(Collect Report Engine?)

**Comment by Score2** [comment]
另外的话，最新版3.7.12应该多了个包，是云防火墙。这个没分析过

**Comment by dpxdp** [comment]
希望可以做一个“解密”版的爱快，将云和一些不必要的模块去掉，贡献openwrt.
用别人开源项目做闭源是个可耻的行为。

**Comment by Score2** [comment]
> 希望可以做一个“解密”版的爱快，将云和一些不必要的模块去掉，贡献openwrt. 用别人开源项目做闭源是个可耻的行为。

没有必要，且存在法律风险。
他们的定位是商业路由系统。

同样的，他们借用开源项目一定会遵循license
否则对他们而言也会存在法律风险。
