### ISSUE TITLE
请教下，那个校验rootfs的hash结果不匹配

### ISSUE THREAD

**Issue by bsdcpp** [2512500960/ikuaifw#2]
```c
	hash_var = __builtin_bswap32(~hash(initrd_start, initrd_size - 4));
	hash_var = __builtin_bswap32(~hash((uint8_t*)&hash_var, 4));
	p_hash = (uint8_t*)(initrd_start + initrd_size - 4);
	if (*(uint32_t*)p_hash == hash_var) {
		printf("success\n");
	}
```
感谢作者的贡献，这里进不到success，校验通不过，算出来的hash_var始终等于0x91ffffff。
可能是类型转换过程的问题还是运行机器的问题？
机器是debian 的Linux debian 6.1.0-23-cloud-amd64
谢谢

**Comment by 2512500960** [comment]
已更新

**Comment by 2512500960** [comment]
源代码是别的大佬的代码，属于面向ida编程，数据类型宽度错误了。
![image](https://github.com/user-attachments/assets/537dcfda-47ba-465f-813a-8ecf9c7c3338)

**Comment by bsdcpp** [comment]
感谢大神修正，已解决。
